### ISSUE TITLE
config renv

### ISSUE THREAD

**Issue by OldLipe** [dataAt/introducao-ao-machine-learning#1]
- isolate the env and regen the `renv.lock`

**Comment by M3nin0** [comment]
@OldLipe Adicionar pacote `rmarkdown` no renv. Isso evita problemas com novas instalações. O que acha ?

**Comment by OldLipe** [comment]
@M3nin0 O `rmakdown` já foi adicionado, o problema é essa quantidade de dep. Vou tentar isolar o ambiente e deixar só os pacotes "necessários".
