### ISSUE TITLE
Classificação | Seleção de atributos

### ISSUE THREAD

**Issue by M3nin0** [dataAt/introducao-ao-machine-learning#4]
`Sugestão`

- Pequeno conteúdo sobre seleção de atributos.

**Comment by M3nin0** [comment]
@OldLipe @AdrianoPereira Pensando aqui, acho que esse tema pode ser generalizado e inserido como uma preocupação que deve estar presente na aplicação de qualquer um dos algoritmos, que acham ? Posso escrever uma seção sobre, ai vemos onde fica na introdução depois·

**Comment by OldLipe** [comment]
@M3nin0 Visto que a decision tree faz a seleção de atributos, acho que basta falar sobre isso quando for falar da DT. Não acho necessário uma seção só para falar de seleção de atributos...

**Comment by M3nin0** [comment]
@OldLipe Mas nesse caso, a ideia da "seleção de atributos" é relacionada a ideia de escolher as características corretas para serem utilizadas nos algoritmos. Por exemplo, posso usar um algoritmo X consumindo de diferentes atributos dos dados. A ideia é colocar isso como algo na introdução, não precisa ser uma seção, mas a apresentação da ideia de que o uso dos algoritmos tem de ser feitos com critérios.

**Comment by AdrianoPereira** [comment]
Acho uma boa ideia, isso poderia se encaixar em um contexto de limpeza dos dados.

**Comment by OldLipe** [comment]
@AdrianoPereira @M3nin0 Acho que isso é um mundo à parte, talvez comentar sobre isso na seção de introdução não sei se vai ficar coerente... acho que na parte da decision tree podemos falar um pouco sobre isso... 

E sobre limpeza de dados, vejo que é algo que não se encaixe nesse curso, limpeza também é à parte., Assim como as normalizações... O que poderiamos fazer, caso queiram de todo jeito adicionar isso, é adicionar uma seção de `Pré-processamento`. Aí nela falamos sobre limpeza, normalização, seleção e essas coisas...

**Comment by M3nin0** [comment]
@AdrianoPereira   @OldLipe Acho que a ideia aqui é mostrar que mesmo os algoritmos, quando frente aos dados, critérios devem ser utilizados, o algoritmos não faz todas as escolhas sozinhos. É nesse sentido, não necessariamente alguma técnica ou seção inteira para isso. A ideia é só deixar claro.
