### ISSUE TITLE
Introdução | Tipos de dados

### ISSUE THREAD

**Issue by M3nin0** [dataAt/introducao-ao-machine-learning#5]
`Sugestão de conteúdo`

- Dentre a escrita, buscar falar sobre os tipos de dados que podem ser utilizados nas classes de algoritmos, não precisa ser nada exaustivo, apenas uma noção intuitiva.

**Comment by OldLipe** [comment]
@M3nin0 Acho que não é necessário, visto que já falamos de tipos  de dados no nosso curso de análise de dados. Apenas uma referência para o minicurso de análise, eu acho que já basta...
