### ISSUE TITLE
Dados do curso | Definição

### ISSUE THREAD

**Issue by M3nin0** [dataAt/introducao-ao-machine-learning#6]
`Sugestão de conteúdos`

- Seção com a descrição geral dos dados utilizados nos exemplos do curso.

**Comment by M3nin0** [comment]
@AdrianoPereira e @OldLipe, o que acham ?

**Comment by OldLipe** [comment]
@M3nin0 Acho que devemos usar exemplos de dados simples, como o `iris` e o `mtcars`. Assim, podemos descrever o conjunto assim quando o usarmos, de forma bem direta. Uma seção para descrever o conjunto de dados não acho necessário...

**Comment by M3nin0** [comment]
Faz sentido, então, na primeira vez que o dado aparecer já explicamos ele.
