### ISSUE TITLE
Estrutura das seções | Definição

### ISSUE THREAD

**Issue by M3nin0** [dataAt/introducao-ao-machine-learning#7]
`Sugestão de estrutura`

Para que o conteúdo de todo o texto seja consistente em termos de estrutura, abaixo apresento minha ideia de estrutura:

- CLASSE DO ALGORITMO
  - Tópicos gerais sobre a classe apresentada

  - Algoritmos
    - NOME DO ALGORITMO
    - Noção intuitiva
    - "formulação" do algoritmo
    - Exemplo de uso (e. g. Python, R)

Exemplo de instância dessa estrutura para os algoritmos de classificação

- CLASSE DO ALGORITMO
  - Tipos de algoritmos de classificação
    - Modelos probabilísticos;
    - Decision Tree
    - Instance-based learning*

- Algoritmos
  - kNN
    - Noção intuitiva
    - "formulação" do algoritmo
    - Exemplo de uso (e. g. Python, R)

**Comment by M3nin0** [comment]
Note que a ideia da `"formulação" do algoritmo` é apresentar o algoritmo em uma estrutura mais "algorítmica", enquanto que na noção intuitiva a ideia mais alto nível será aplicada

**Comment by M3nin0** [comment]
O que acham @AdrianoPereira @OldLipe ?

**Comment by OldLipe** [comment]
> Note que a ideia da `"formulação" do algoritmo` é apresentar o algoritmo em uma estrutura mais "algorítmica", enquanto que na noção intuitiva a ideia mais alto nível será aplicada

@M3nin0 Acho que isso deve ser no máximo de dois paragrafos, nada detalhado demais. Temos que lembrar que estamos escrevendo para publico geral, e não somente computeiros...



@M3nin0 Sobre a estrutura eu concordo. Embaixo do jeito que penso que deva ficar a estrutura. Eu não gosto de termos uma subseção chamada `algoritmos`. Acho que as subseções podem ser os próprios algoritmos...

2. Classificação 
2.1. KNN
2.2. Algoritmo X
2.2. Algoritmo Y

**Comment by M3nin0** [comment]
Beleza, concordo com o que você disse da seção de algoritmos.

**Comment by M3nin0** [comment]
@OldLipe podemos fechar a estrutura para a escrita dessa forma ?

**Comment by AdrianoPereira** [comment]
Eu acharia interessante ter uma descrição mais aprofundada dos algoritmos, como o @M3nin0 sugeriu, mas tbm o @OldLipe  tem razão, para um publico geral talvez não seja uma boa ideia, vamos decidir no Jokepo.

**Comment by OldLipe** [comment]
@AdrianoPereira Mas o que seria uma descrição aprofundada? Não acho necessário porque as bibliotecas impletam os algortimos em alto nível. Pra mim, apenas uma breve descrição (um paragrafo), só descrevendo por cima o algoritmo...

**Comment by M3nin0** [comment]
Para tornar o processo mais direto e simples de ler, vamos retirar essa parte. A ideia não era realizar algo aprofundado, mas sim mostrar um ponto de vista mais organizado, logo após a apresentação de uma idea intuitiva, por exemplo:

- kNN (Exemplo de texto com noção intuitiva)

kNN é um algoritmo que através da similaridade entre os vizinhos da amostra que está sendo classificada determina a classe deste. Aqui a lógica "Me diga com quem tu andas que digo quem tu és" é aplicada o tempo tempo [...]

- Parte 'algoritmica'

Agora que já foi apresentada uma visão intuitiva do algoritmo, aqui é feita a apresentação geral dos passos de funcionamento do mesmo

1. Dado um ponto, este é colocado no plano cartesiano junto a outras amostras
2. Faz-se a determinação dos vizinhos mais próximos calculando a distância entre o ponto inserido e todos os demais no espaço
3. Classifica a amostra inserida com base na moda da classe dos vizinhos.

Era algo assim, não precisa também necessariamente ser algo em seções separadas. A ideia é meio que seguirmos um padrão de estrutura. Coloquei dessa forma por ter consumido livros que fazem dessa maneira, como o **Data Classification** do Aggarwal.

**Comment by M3nin0** [comment]
@OldLipe @AdrianoPereira Acho que, por nossas definições, feitas anteriormente, vamos seguir esse padrão mesmo. Vou fechar a issue e qualquer coisa abrimos novamente.
