### ISSUE TITLE
Termos | Revisão

### ISSUE THREAD

**Issue by M3nin0** [dataAt/introducao-ao-machine-learning#8]
Isso vai ser feito depois, mas acho interessante já deixar anotado. Durante a revisão, verificar os termos que estão sendo utilizados nos capítulos, eles precisam ser coerentes

**Comment by M3nin0** [comment]
@AdrianoPereira @OldLipe marquem os padrões que vocês utilizaram e coloquem aqui, depois fica mais fácil mapear depois.

**Comment by OldLipe** [comment]
Conteúdo de agrupamento - padrões:

- Objeto
- Não supervisionado
- Supervisionado
- _Overfitting
- _Underfitting_
- Plano cartesiano (será que precisa explicar) 
- Rótuio

Termos computacionais:

- Iteração

**Comment by M3nin0** [comment]
> 
> 
> Conteúdo de agrupamento - padrões:
> 
>     * Objeto
> 
>     * Não supervisionado
> 
>     * Supervisionado
> 
>     * _Overfitting
> 
>     * _Underfitting_
> 
>     * Plano cartesiano (será que precisa explicar)
> 
>     * Rótuio
> 
> 
> Termos computacionais:
> 
>     * Iteração

Essas formas exatamente as definições que encontrei realizando a revisão agora
